# Multiple Linear Regression

**Import Libraries**

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x: '%.2f' % x)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score

**Read csv file**

In [2]:
df = pd.read_csv('advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0 230.10  37.80      69.20  22.10
1  44.50  39.30      45.10  10.40
2  17.20  45.90      69.30   9.30
3 151.50  41.30      58.50  18.50
4 180.80  10.80      58.40  12.90

**Features and Label**

In [4]:
X = df.drop('sales', axis=1)
y = df[['sales']]

**Model**

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [16]:
reg_model = LinearRegression()
reg_model.fit(X_train, y_train)

LinearRegression()

In [17]:
reg_model.intercept_

array([2.90794702])

In [18]:
reg_model.coef_

array([[0.0468431 , 0.17854434, 0.00258619]])

**Model evaluation**

In [19]:
y_predictions = reg_model.predict(X_train)

In [20]:
y_predictions

array([[ 3.65921577],
       [ 7.25612637],
       [ 6.00481636],
       [18.46169785],
       [ 8.37406584],
       [14.12454209],
       [15.0161764 ],
       [20.40205426],
       [20.61382233],
       [19.61731651],
       [24.16323248],
       [14.88403603],
       [ 6.73108467],
       [19.86205547],
       [18.92113796],
       [12.49612522],
       [14.17816602],
       [ 6.11982211],
       [15.33821244],
       [ 9.59951578],
       [12.04789746],
       [12.04846338],
       [ 8.52368581],
       [21.61141557],
       [23.30426145],
       [12.24026439],
       [ 6.68855681],
       [17.80465348],
       [16.50075138],
       [ 8.78138524],
       [20.39682769],
       [20.67376942],
       [24.24311844],
       [10.16119323],
       [10.51556751],
       [16.43194712],
       [10.46014901],
       [ 6.66787113],
       [21.36473141],
       [14.43134771],
       [15.49693622],
       [10.09789459],
       [14.96838524],
       [13.86965306],
       [ 8.38839734],
       [ 8

**Model evaluation train set**

In [33]:
# mean squared error
mean_squared_error(y_train, y_predictions)

3.0168306076596774

In [34]:
# root mean squared error
np.sqrt(mean_squared_error(y_train, y_predictions))

1.736902590147092

In [27]:
# mean absolute error
mean_absolute_error(y_predictions, y_train)

1.3288502460998386

In [31]:
# r-square
reg_model.score(X_train, y_train)

0.8959372632325174

**Model evaluation test set**

In [32]:
y_test_predict = reg_model.predict(X_test)

In [37]:
# mean squared error
mean_squared_error(y_test, y_test_predict)

1.9918855518287892

In [38]:
# root mean squared error
np.sqrt(mean_squared_error(y_test, y_test_predict))

1.4113417558581582

In [39]:
# mean absolute error
mean_absolute_error(y_test_predict, y_test)

1.0402154012924716

In [41]:
# r-square
reg_model.score(X_test, y_test)

0.8927605914615384

**K-Fold Cross Validation**

In [45]:
np.mean(np.sqrt(-cross_val_score(reg_model, X, y, cv=10, scoring='neg_mean_squared_error')))

1.6913531708051792